### PR TITLE
Django 1.10 compability.

### PR DESCRIPTION
**Pull request by kierun**
See [issue 29](https://github.com/tabo/django-treebeard/pull/29)…

### CODE REVIEW

**Comment by JoshAddington** [comment]
See PR #33

**Comment by kierun** [comment]
I do not care which PR you use, but this needs fixing as per issue 29. I edited the code on master as of yesterday to create this PR.

**Comment by JoshAddington** [comment]
It sure does need fixing, so we're all waiting @tabo for the merge of #33. Opening another PR isn't going to get the issue fixed sooner, especially when a previous PR is a more complete fix.

**Comment by kierun** [comment]
@tabo, so when can we expect support for 1.10?

**Comment by kcolton** [comment]
@kierun ... broken recording here:

@BeOleg #33 Is pretty solid - we are running production with it and have only run into 1 issue with `MoveNodeForm` which has been merged into #33. 

Unless this is adding *new* fixes - I think closing and supporting #33 

Depending on your requirements and deployment setup, the safest way is to download a zip of #33 from https://github.com/fladi/django-treebeard/tree/django-1.10, bump the version number in `setup.py` (so something like heroku will realize the change) and reference in your requirements file like:

`./deploy/requirements/django-treebeard-4.0.3unofficial.zip`

@JoshAddington is correct - the more people running against and supporting #33, the more bugs will be found, the less PRs with overlap (suggest closing this one) the faster this can get merged when @tabo has availability.

**Comment by tabo** [comment]
Thanks for the PR, but #33 has already been merged.

**Pull request closed without merging**
