### PR TITLE
Remove unused `patterns` import

### PR DESCRIPTION
**Pull request by aidaho**
Fixes crash with Django 1.10.
https://docs.djangoproject.com/en/1.10/releases/1.10/#features-removed-in-1-10

### CODE REVIEW

**Comment by Alex3917** [comment]
Apropos of this pull request, are there any plans to re-enable the issues tab for this project? For people relying on this as a dependency in their project, it's difficult to figure out what's broken unless there's a way to see what other folks have reported.

**Comment by qmarlats** [comment]
+1 for enabling issues and +1 for the pull request

**Comment by Ubica** [comment]
+1 for this, was just about to do it myself

**Comment by yakky** [comment]
@tabo Any help needed to get this merged?

**Comment by tabo** [comment]
Thanks for the PR, but #33 has already been merged.

**Pull request closed without merging**
