### PR TITLE
compability with Django 1.10

### PR DESCRIPTION
**Pull request by Arany**
get_urls function:
* Using list instead patterns function
* importing Django javascript_catalog instead of using string name

### CODE REVIEW

**Comment by kjg531** [comment]
+1 please merge this!

**Comment by qnub** [comment]
@tabo have you checked GitHub?

**Comment by SalahAdDin** [comment]
Solve this these bugs?

```bash
/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/treebeard/admin.py:62: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.views.i18n.javascript_catalog). Pass the callable instead.
  {'packages': ('treebeard',)}),

/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/treebeard/admin.py:62: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  {'packages': ('treebeard',)}),
```

**Comment by Arany** [comment]
@SalahAdDin: Yes, that is what the pullrequest is for.
@tabo: Now Django 1.10 is out and django-treebeard is not any more compatible with it. Please check this PR out..

**Comment by kierun** [comment]
Django 1.10.0 has been out for a little while now. It would be nice for this to be merged…

**Comment by tabo** [comment]
Merged! Thanks for the PR!

**Comment by kierun** [comment]
Now, that is awesome! I was just writing a note in our internal mantis that I could not update because of this… Thank you very much.

**Comment by kierun** [comment]
Quick question, are you planning to release it a new version soon? Just so I know if I should run the latest bleeding edge or wait for a few hours. ;)

**Comment by tabo** [comment]
Yep! Will work on that during the weekend :)

**Comment by kierun** [comment]
I noticed there is still a bug there: In `treebeard/admin.py`,

`from django.conf.urls import pattern, url`

should read:

`from django.conf.urls import url`

Do you want me to make a pull request or is it way too trivial for that?

**Comment by kcolton** [comment]
@tabo @kierun Thanks for the updates. That 1 last line, regardless of how entered would be appreciated. We are running off a fork with that 1 change just to get 1.10 going. :) Cheers and thanks for your efforts!

**Pull request merged**
